# Generated by Django 4.2.3 on 2023-09-04 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workschedule", "0002_hospital_shift_delete_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospital",
            old_name="hospname",
            new_name="name",
        ),
    ]
