# Generated by Django 4.2.3 on 2023-09-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workschedule", "0004_alter_hospital_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalinfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item1",
                    models.CharField(choices=[("可", "可"), ("不可", "不可")], max_length=2),
                ),
                (
                    "item2",
                    models.CharField(choices=[("可", "可"), ("不可", "不可")], max_length=2),
                ),
                (
                    "item3",
                    models.CharField(choices=[("可", "可"), ("不可", "不可")], max_length=2),
                ),
                (
                    "item4",
                    models.CharField(choices=[("可", "可"), ("不可", "不可")], max_length=2),
                ),
                (
                    "item5",
                    models.CharField(choices=[("可", "可"), ("不可", "不可")], max_length=2),
                ),
                (
                    "item6",
                    models.CharField(choices=[("可", "可"), ("不可", "不可")], max_length=2),
                ),
                (
                    "item7",
                    models.CharField(choices=[("可", "可"), ("不可", "不可")], max_length=2),
                ),
                (
                    "item8",
                    models.CharField(choices=[("可", "可"), ("不可", "不可")], max_length=2),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="shift",
            name="hospital",
        ),
        migrations.DeleteModel(
            name="Hospital",
        ),
        migrations.DeleteModel(
            name="Shift",
        ),
    ]
