# Generated by Django 4.2.3 on 2023-09-09 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workschedule", "0005_personalinfomodel_remove_shift_hospital_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfomodel",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="personalinfomodel",
            name="item1",
            field=models.CharField(
                choices=[("可", "可"), ("不可", "不可")], max_length=2, verbose_name="大学"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfomodel",
            name="item2",
            field=models.CharField(
                choices=[("可", "可"), ("不可", "不可")], max_length=2, verbose_name="取手"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfomodel",
            name="item3",
            field=models.CharField(
                choices=[("可", "可"), ("不可", "不可")], max_length=2, verbose_name="高萩"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfomodel",
            name="item4",
            field=models.CharField(
                choices=[("可", "可"), ("不可", "不可")], max_length=2, verbose_name="日赤"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfomodel",
            name="item5",
            field=models.CharField(
                choices=[("可", "可"), ("不可", "不可")], max_length=2, verbose_name="大学"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfomodel",
            name="item6",
            field=models.CharField(
                choices=[("可", "可"), ("不可", "不可")], max_length=2, verbose_name="学園"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfomodel",
            name="item7",
            field=models.CharField(
                choices=[("可", "可"), ("不可", "不可")], max_length=2, verbose_name="龍ヶ崎"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfomodel",
            name="item8",
            field=models.CharField(
                choices=[("可", "可"), ("不可", "不可")], max_length=2, verbose_name="セントラル"
            ),
        ),
    ]
