# Generated by Django 4.2.3 on 2023-09-21 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "workschedule",
            "0006_personalinfomodel_user_alter_personalinfomodel_item1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfomodel",
            name="item1",
            field=models.CharField(
                choices=[("可", "可"), ("不可", "不可")], max_length=2, verbose_name="大学当直"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfomodel",
            name="item2",
            field=models.CharField(
                choices=[("可", "可"), ("不可", "不可")], max_length=2, verbose_name="取手当直"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfomodel",
            name="item3",
            field=models.CharField(
                choices=[("可", "可"), ("不可", "不可")], max_length=2, verbose_name="高萩当直"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfomodel",
            name="item4",
            field=models.CharField(
                choices=[("可", "可"), ("不可", "不可")], max_length=2, verbose_name="日赤当直"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfomodel",
            name="item5",
            field=models.CharField(
                choices=[("可", "可"), ("不可", "不可")], max_length=2, verbose_name="大学オンコール"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfomodel",
            name="item6",
            field=models.CharField(
                choices=[("可", "可"), ("不可", "不可")], max_length=2, verbose_name="学園オンコール"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfomodel",
            name="item7",
            field=models.CharField(
                choices=[("可", "可"), ("不可", "不可")],
                max_length=2,
                verbose_name="龍ヶ崎オンコール",
            ),
        ),
        migrations.AlterField(
            model_name="personalinfomodel",
            name="item8",
            field=models.CharField(
                choices=[("可", "可"), ("不可", "不可")],
                max_length=2,
                verbose_name="セントラルオンコール",
            ),
        ),
        migrations.CreateModel(
            name="ShiftAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "on_call_available",
                    models.BooleanField(default=False, verbose_name="当直可"),
                ),
                (
                    "on_call_comments",
                    models.TextField(blank=True, verbose_name="当直コメント"),
                ),
                (
                    "on_call_external_hospital",
                    models.BooleanField(default=False, verbose_name="外病院当直可"),
                ),
                (
                    "on_call_external_hospital_comments",
                    models.TextField(blank=True, verbose_name="外病院当直コメント"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "当直可否入力",
                "verbose_name_plural": "当直可否入力一覧",
            },
        ),
        migrations.CreateModel(
            name="CalendarDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("希望", "希望"), ("不可", "不可"), ("どちらでもない", "どちらでもない")],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
